on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v2
      - uses: ./.github/actions/hello-world-action
        id: hello
        with:
          who-to-greet: 'My Butt'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
        